version: '3.7'

services:
  app:
    hostname: texecom-simple-ui
    image: 'texecom-simple-ui:latest'
    build: .
    restart: unless-stopped
    environment:
      - TEXE_USERNAME
      - TEXE_PASSWORD
      - TEXE_USER_CODE
      - DUMMY_DATA
      - TOKEN
      - PANEL_ID
    networks:
      - shared-private
      - default

networks:
  shared-private:
    external: true
    name: core-local-infra_shared-private
