version: "3.7"

services:
  app:
    image: "texecom-simple-ui:latest"
    build: .
    restart: unless-stopped
    ports:
      - "8080:3000"
    environment:
      - TEXE_USERNAME
      - TEXE_PASSWORD
      - TEXE_USER_CODE
      - DUMMY_DATA
      - TOKEN
      - PANEL_ID
      - LOCAL_AUTH_USERNAME
      - LOCAL_AUTH_PASSWORD
