name: CI

on: [push, pull_request]

env:
  npm_config_engine_strict: true
  MISE_IDIOMATIC_VERSION_FILE_ENABLE_TOOLS: 'node,pnpm'

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v7
      - name: Setup mise
        uses: jdx/mise-action@v5

      - run: pnpm ci
      - name: build docker image
        run: pnpm run docker:build
